### ISSUE TITLE
The resource of datasets

### ISSUE THREAD

**Issue by Bigggapple** [kevinscaria/InstructABSA#19]
Hello,

I have some confusion regarding the datasets provided in your Git repository. In your paper, you mentioned that the benchmarks are sourced from the original SemEval 14, 15, and 16. However, I noticed that you included Peng's datasets in your repository. While Peng's datasets are refined versions of the SemEval data, there are still some differences between the two. Therefore, I would like to know which resources your test results are based on. Thank you for your attention to this matter.

**Comment by kevinscaria** [comment]
Hello, 
The revised version of the paper is not been updated due to anonymity period violations. However to clarify your doubt, for the standard ATE, ATSC and Joint Task we use the benchmark datasets. For tasks such as opinion term extraction and triplet extraction we use Peng's dataset.

Best, 
KJS
